server:
  port: 8098

spring:
  profiles:
    active: docker
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

---
spring:
  profiles: dev
  kafka:
    bootstrap-servers: localhost:9092

---
spring:
  profiles: docker
  kafka:
    bootstrap-servers: kafka:9092
